theme: jekyll-theme-midnight
title: Online Experiments for Language Scientists
description: Academic year 2026-2027
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
