#theme: jekyll-theme-midnight
remote_theme: pages-themes/leap-day@v0.2.0
title: Online Experiments for Language Scientists
description: Academic year 2026-2027
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
